// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © davidriogita

//@version=5
indicator(title="TPI", shorttitle= "TPI Alert", overlay=true, max_bars_back = 21)

macd_signal() =>
    fast = 12
    slow = 26
    fastMA = ta.ema(close, fast)
    slowMA = ta.ema(close, slow)
    macd = fastMA - slowMA
    signal = ta.ema(macd, 9)
    valore = 0
    if macd > signal
        valore := 1
    else if macd == signal
        valore := 0
    else
        valore := -1

valore = macd_signal()
plot(valore, color = color.blue)


// plot(close)
