// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © davidriogita

//@version=5
indicator(title="TPI", shorttitle= "TPI Alert", overlay=true, max_bars_back = 21)

// 1 - AROON
aroon_signal() =>
    length = input.int(14, minval=1)
    upper = 100 * (ta.highestbars(high, length+1) + length)/length
    lower = 100 * (ta.lowestbars(low, length+1) + length)/length
    if upper > lower
        valore = 1
    else if upper == lower
        valore = 0
    else
        valore = -1


// 2 - DMI
dmi_signal() =>
    len = input.int(14, minval=1, title="DI Length")
    lensig = input.int(14, title="ADX Smoothing", minval=1, maxval=50)
    [diplus, diminus, adx] = ta.dmi(len, lensig)
    if diplus > diminus
        valore = 1
    else if diplus == diminus
        valore = 0
    else
        valore = -1


// 3 - MACD Signal
macd_signal() =>
    fast = 12
    slow = 26
    fastMA = ta.ema(close, fast)
    slowMA = ta.ema(close, slow)
    macd = fastMA - slowMA
    signal = ta.ema(macd, 9)
    if macd > signal
        valore = 1
    else if macd == signal
        valore = 0
    else
        valore = -1




// 4 - Parabolic SAR
// 5 - RSI
// 6 - SUPERTREND
// 7 - SMI


aroon_value = aroon_signal()
dmi_value = dmi_signal()
macd_value = macd_signal()

plot(macd_value, color = color.blue)


// plot(close)
